```js
{ inNode: '8.11.1',
  animationFrameRequested: false,
  onAnimationFrame: [Function],
  suppressAnimationLoop: true,
  loopWhileDisconnected: true,
  frameEventName: 'deviceFrame',
  useAllPlugins: false,
  history:
   { pos: 4696,
     _buf:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        ... 100 more items ],
     size: 200 },
  lastFrame:
   { valid: true,
     id: 236286,
     timestamp: 31369460025,
     hands: [],
     handsMap: {},
     pointables: [],
     tools: [],
     fingers: [],
     interactionBox:
      { valid: true,
        center: [Array],
        size: [Array],
        width: 235.247,
        height: 235.247,
        depth: 147.751 },
     gestures: [],
     pointablesMap: {},
     _translation: [ 0, 0, 0 ],
     _rotation: [ 1, 0, 0, 0, 1, 0, 0, 0, 1 ],
     _scaleFactor: 1,
     data:
      { currentFrameRate: 81.192,
        devices: [],
        gestures: [],
        hands: [],
        id: 236286,
        interactionBox: [Object],
        pointables: [],
        r: [Array],
        s: 1,
        t: [Array],
        timestamp: 31369460025 },
     type: 'frame',
     currentFrameRate: 81.192,
     controller: [Circular],
     historyIdx: 4695 },
  lastValidFrame:
   { valid: true,
     id: 236286,
     timestamp: 31369460025,
     hands: [],
     handsMap: {},
     pointables: [],
     tools: [],
     fingers: [],
     interactionBox:
      { valid: true,
        center: [Array],
        size: [Array],
        width: 235.247,
        height: 235.247,
        depth: 147.751 },
     gestures: [],
     pointablesMap: {},
     _translation: [ 0, 0, 0 ],
     _rotation: [ 1, 0, 0, 0, 1, 0, 0, 0, 1 ],
     _scaleFactor: 1,
     data:
      { currentFrameRate: 81.192,
        devices: [],
        gestures: [],
        hands: [],
        id: 236286,
        interactionBox: [Object],
        pointables: [],
        r: [Array],
        s: 1,
        t: [Array],
        timestamp: 31369460025 },
     type: 'frame',
     currentFrameRate: 81.192,
     controller: [Circular],
     historyIdx: 4695 },
  lastConnectionFrame:
   { valid: true,
     id: 236286,
     timestamp: 31369460025,
     hands: [],
     handsMap: {},
     pointables: [],
     tools: [],
     fingers: [],
     interactionBox:
      { valid: true,
        center: [Array],
        size: [Array],
        width: 235.247,
        height: 235.247,
        depth: 147.751 },
     gestures: [],
     pointablesMap: {},
     _translation: [ 0, 0, 0 ],
     _rotation: [ 1, 0, 0, 0, 1, 0, 0, 0, 1 ],
     _scaleFactor: 1,
     data:
      { currentFrameRate: 81.192,
        devices: [],
        gestures: [],
        hands: [],
        id: 236286,
        interactionBox: [Object],
        pointables: [],
        r: [Array],
        s: 1,
        t: [Array],
        timestamp: 31369460025 },
     type: 'frame',
     currentFrameRate: 81.192,
     controller: [Circular],
     historyIdx: 4695 },
  accumulatedGestures: [],
  checkVersion: true,
  connectionType: [Function],
  connection:
   { opts:
      { frameEventName: 'deviceFrame',
        enableGestures: true,
        inNode: '8.11.1',
        suppressAnimationLoop: true,
        loopWhileDisconnected: true,
        useAllPlugins: false,
        checkVersion: true,
        host: '127.0.0.1',
        scheme: 'ws:',
        port: 6437,
        background: false,
        optimizeHMD: false,
        requestProtocolVersion: 6 },
     host: '127.0.0.1',
     port: 6437,
     scheme: 'ws:',
     protocolVersionVerified: true,
     background: false,
     optimizeHMD: false,
     _events:
      { ready: [Array],
        frame: [Array],
        focus: [Function],
        blur: [Function],
        protocol: [Function],
        connect: [Function],
        disconnect: [Function],
        deviceConnect: [Function],
        deviceEvent: [Function] },
     _eventsCount: 9,
     socket:
      WebSocket {
        _socket: [Object],
        bytesReceived: 4608693,
        readyState: 1,
        supports: [Object],
        _isServer: false,
        url: 'ws://127.0.0.1:6437/v6.json',
        protocolVersion: 13,
        _events: [Object],
        _eventsCount: 4,
        _receiver: [Object],
        _sender: [Object] },
     connected: true,
     protocol:
      { [Function: protocol]
        encode: [Function],
        version: 6,
        serviceVersion: '2.3.1+31549',
        versionLong: 'Version 6',
        type: 'protocol',
        domain: undefined,
        _events: [Object],
        _maxListeners: undefined,
        setMaxListeners: [Function: setMaxListeners],
        getMaxListeners: [Function: getMaxListeners],
        emit: [Function: emit],
        addListener: [Function: addListener],
        on: [Function: addListener],
        prependListener: [Function: prependListener],
        once: [Function: once],
        prependOnceListener: [Function: prependOnceListener],
        removeListener: [Function: removeListener],
        removeAllListeners: [Function: removeAllListeners],
        listeners: [Function: listeners],
        listenerCount: [Function: listenerCount],
        eventNames: [Function: eventNames],
        sendBackground: [Function],
        sendFocused: [Function],
        sendOptimizeHMD: [Function],
        _eventsCount: 2 },
     gesturesEnabled: true,
     focusedState: true },
  streamingCount: 1,
  devices:
   { LP78705255113:
      { attached: true,
        id: 'LP78705255113',
        streaming: true,
        type: 'peripheral' } },
  plugins: {},
  _pluginPipelineSteps: {},
  _pluginExtendedMethods: {},
  _events:
   { deviceFrame: [Function],
     newListener: [Function],
     connect: [Function],
     ready: [Function],
     deviceStreaming: [Function],
     deviceStopped: [Function],
     disconnect: [Function],
     frame: [Function] },
  _eventsCount: 8 }
```